spring:
  application:
    name: yioj-backend-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: yioj-backend-user-service
          uri: lb://yioj-backend-user-service
          predicates:
            - Path=/api/user/**

        - id: yioj-backend-question-service
          uri: lb://yioj-backend-question-service
          predicates:
            - Path=/api/question/**

        - id: yioj-backend-judge-service
          uri: lb://yioj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  main:
    web-application-type: reactive
server:
  port: 8201

# 网关接口文档配置
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2
